os: Visual Studio 2015

environment:
  matrix:
  - platform: X86
    compiler: "Visual Studio 14 2015"
    configuration: Release
  - platform: X86
    compiler: "Visual Studio 14 2015"
    configuration: Debug
  - platform: X64
    compiler: "Visual Studio 14 2015 Win64"
    configuration: Release
  - platform: X64
    compiler: "Visual Studio 14 2015 Win64"
    configuration: Debug

install:
  - curl http://releases.llvm.org/5.0.0/llvm-5.0.0.src.tar.xz -o llvm.tar.xz
  - 7z x llvm.tar.xz
  - 7z x llvm.tar -ollvm
build_script:
  - mkdir llvm\llvm-5.0.0.src\build && cd llvm\llvm-5.0.0.src\build
  - cmake .. -G "%compiler%" -DLLVM_TARGETS_TO_BUILD=%platform% -DLLVM_BUILD_TESTS=Off -DCMAKE_INSTALL_PREFIX="./llvm"
  - cmake --build . --config %configuration%
  - cmake --build . --target install

notifications:

  - provider: Email
    on_build_status_changed: false
