
configuration: Release
os: Visual Studio 2015

environment:
  matrix:
  - platform: X86
    compiler: "Visual Studio 14 2015"
  - platform: X64
    compiler: "Visual Studio 14 2015 Win64"

install:
  - curl http://releases.llvm.org/5.0.0/llvm-5.0.0.src.tar.xz -o llvm.tar.xz
  - 7z x llvm.tar.xz
  - 7z x llvm.tar -ollvm
build_script:
  - cd llvm\llvm-5.0.0.src && mkdir build && cd build
  - cmake .. -G "%compiler%" -DLLVM_TARGETS_TO_BUILD=%platform% -DLLVM_BUILD_TESTS=Off -DCMAKE_INSTALL_PREFIX="./llvm"
  - cmake --build .
  - cmake --build . --target install

notifications:

  - provider: Email
    on_build_status_changed: false
